### ISSUE TITLE
Date Picker icon not clickable

### ISSUE THREAD

**Issue by tastrax** [lutraconsulting/input#1104] opened 2021-01-19 11:14 UTC
IOS v0.7.8 - Using the 'Capturing Field data tour' - the date picker icon doesn't open the calendar (unlike up/down arrows for picklists). You need to click to the left of the icon to access the calendar widget.

**Comment by saberraz** [comment] 2021-01-22 08:04
@mostlyAtNight could you have a look. It is not appearing at all for me.

**Comment by saberraz** [comment] 2021-05-06 10:36
Related and duplicate of #1377

**Closed by saberraz** 2021-05-06 10:36 UTC
Labels: bug, iOS
