### ISSUE TITLE
(local) projects from different Mergin accounts are accessible 

### ISSUE THREAD

**Issue by tastrax** [lutraconsulting/input#454] opened 2019-09-15 02:38 UTC
Let’s say I work for two businesses – I want to be able to login to Input and ONLY see the projects for Business A or Business B using that login. It appears at the moment that I see all projects for Business A and B regardless of login

IOS version

**Comment by PeterPetrik** [comment] 2019-09-16 07:07
Hi, this is due to the fact that the mergin is used only as download/upload/sync agent. Once the project is on device it is visible even when logout.

this is due you can also manually copy the projects via USB cable to the INPUT location (without mergin at all).

**Comment by PeterPetrik** [comment] 2019-09-16 07:10
duplicate of #453

**Closed by PeterPetrik** 2019-09-16 07:10 UTC
Labels: enhancement
