### ISSUE TITLE
Unified QML formatting style

### ISSUE THREAD

**Issue by sklencar** [lutraconsulting/input#1240] opened 2021-03-09 08:20 UTC
Let's have a unified format styling for QML code. Feel free to come up with some styling or any ideas.

[QML Coding conventions](https://doc.qt.io/qt-5/qml-codingconventions.html)

**Comment by tomasMizera** [comment] 2021-03-16 17:04
Let's unify also attribute names exposed in `roleNames` function from cpp models. Sometimes one does not know if it is property in QML or coming from cpp, especially when delegate is as extra component in different file.

We could e.g. always use `model.xyz`

**Comment by tomasMizera** [comment] 2021-09-28 08:42
https://github.com/Orange-OpenSource/qmljsreformatter

**Comment by tomasMizera** [comment] 2021-09-28 08:43
https://github.com/jesperhh/qmlfmt

**Comment by PeterPetrik** [comment] 2021-12-21 07:24
duplicate of https://github.com/lutraconsulting/input/issues/1799

**Closed by PeterPetrik** 2021-12-21 07:24 UTC
