### ISSUE TITLE
Please add the language selection function. Can't display Chinese.

### ISSUE THREAD

**Issue by dfwsbylwy** [lutraconsulting/input#1615] opened 2021-08-30 23:12 UTC
As described in the title

**Comment by PeterPetrik** [comment] 2021-08-31 14:10
Thanks for translating to Chinese. The new language in the app must be compiled and released, which was not case for tthe Chinese and I fixed it today by https://github.com/lutraconsulting/input/commit/06b316fbdfe9da7812d05152ecab2a82a6ef61c3 The lang should be available in the next (1.0.0) release if your phone primary/first language is Chinese.

**Comment by PeterPetrik** [comment] 2021-08-31 14:10
the other enhancement is duplicate of https://github.com/lutraconsulting/input/issues/743

**Closed by PeterPetrik** 2021-08-31 14:10 UTC
Labels: duplicate
