### ISSUE TITLE
GPS and app in background

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#80] opened 2018-11-27 19:48 UTC
When the app is in background and no data capturing is in progress, it keeps the GPS on. I have the close the application to stop the GPS usage. This will cause battery drain.

**Comment by wonder-sk** [comment] 2018-11-27 19:52
Right, we should only keep GPS on in case we are recording.

**Comment by saberraz** [comment] 2019-02-16 07:20
In the latest version, this bug resurfaced.

**Comment by wonder-sk** [comment] 2019-02-20 14:10
Confirmed - caused by the fact we currently build Input using a patched version of QGIS 3.4.x while the fix is only available in QGIS 3.6

**Comment by wonder-sk** [comment] 2019-03-04 13:05
Fixed in the newest build

**Closed by wonder-sk** 2019-03-04 13:05 UTC
Labels: enhancement
