### ISSUE TITLE
iPad scribble with Apple Pencil 

### ISSUE THREAD

**Issue by jdelbridge** [lutraconsulting/input#1754] opened 2021-11-15 05:18 UTC
It would be great if values could be entered using the scribble function on an iPad with an Apple Pencil. Thank you!

**Comment by tomasMizera** [comment] 2021-11-25 10:39
Hi @jdelbridge, thanks for the feedback!
Scribble (just like handwrite on Samsung) should be provided out of the box by default system keyboard. Have you tried using the scribble on your iPad in Input? If not, could you please test it and let us know if that worked? Please reopen the issue or comment here if it does not work.

Here is an example from Samsung's handwrite with stylus:

https://user-images.githubusercontent.com/22449698/143426036-7fe27215-e92b-4217-902f-e4ea0e0d5e12.mp4

**Comment by saberraz** [comment] 2021-11-25 10:43
The ticket is related to drawing geometries using the stylus.

**Comment by saberraz** [comment] 2022-03-25 08:40
Duplicate of https://github.com/lutraconsulting/input/issues/1754

**Closed by saberraz** 2022-03-25 08:40 UTC
Labels: enhancement, iOS
