### ISSUE TITLE
Inactive Project Error

### ISSUE THREAD

**Issue by banbar** [lutraconsulting/input#494] opened 2019-10-28 14:20 UTC
I am using Huawei P8 lite and I successfully downloaded the app. I am using Android version 8.0.0. However, when I explore new projects and add them, they appear at the 'Home' tab, but they are not active. 

![Screenshot_20191028-171438](https://user-images.githubusercontent.com/20798817/67685863-dd0cc600-f9a6-11e9-9470-579ae972aa58.jpg)

**Comment by saberraz** [comment] 2019-10-28 14:25
hi @banbar could you "close" the app (by swiping the app from window) and restart it again?

**Comment by saberraz** [comment] 2019-10-28 14:28
Could you clear your cache under app settings and try again?

**Comment by banbar** [comment] 2019-10-28 14:46
Didn't work out.

**Comment by saberraz** [comment] 2019-10-28 14:50
Could you check if the app has permission to read/write to your storage?

**Comment by banbar** [comment] 2019-10-28 14:53
Yes, it does.

**Comment by saberraz** [comment] 2019-10-28 15:01
Are you logged in to Mergin?

**Comment by banbar** [comment] 2019-10-28 15:04
Yes

**Comment by saberraz** [comment] 2019-10-28 15:06
Does it happen to **My Projects** or **Shared with me** projects too? Or just the projects under **Explore**?

**Comment by banbar** [comment] 2019-11-04 09:58
It happens to projects that are shared with me as well as the ones I download from Explore.

**Comment by saberraz** [comment] 2019-11-04 10:05
I am not able to reproduce the issue. Which version of Input are you using?

**Comment by banbar** [comment] 2019-11-04 10:53
0.4.4

**Comment by dracic** [comment] 2019-11-29 07:41
@saberraz, I have the same issue on some Huawei (Y6 2018, Android 8.0.0) phones. We use 0.4.9 Beta. As I can't see "INPUT/Projects" folder after project download on internal memory root I'm guessing that it has something with permissions (everything is allowed in app permissions) or filesystem.

**Comment by saberraz** [comment] 2019-11-29 08:08
Hmmmm... Could you check:

- if there is enough storage available?
- If there is a custom permission manager in addition to Android default one?
- if you are using the external storage?

**Comment by dracic** [comment] 2019-11-29 08:20
- Yes. That was our first guess, but we have enough space.
- No, just the default one.
- You mean for the app location? Apps are installed to internal memory.

**Comment by wonder-sk** [comment] 2019-11-29 08:28
If you look into the project directory with a file browser, are the project files downloaded there? Especially .qgs / .qgz file - is it present?

**Comment by dracic** [comment] 2019-11-29 08:45
No there is no INPUT/Projects directory at all, that's why I said i suppose there is something with Huawei filesystem or permission logic.

**Comment by saberraz** [comment] 2021-04-21 08:44
@dracic is this still the case? Or has been addressed by ROM upgrade?

**Comment by dracic** [comment] 2021-04-21 09:08
We don't have any Y6, but just now I contacted my colleague with P40 Lite (Android 10) and everything works OK.

**Comment by saberraz** [comment] 2021-04-21 09:09
Brilliant! Thanks for confirming.

**Closed by saberraz** 2021-04-21 09:09 UTC
Labels: blocked upstream, blocker, bug
