### ISSUE TITLE
Cannot sign in mergin

### ISSUE THREAD

**Issue by berkayoruc** [lutraconsulting/input#473] opened 2019-09-26 13:44 UTC
`Ubuntu - for Android`
Hello. I builded 'input' but I cannot sign in mergin with input which was builded by me. Otherwise, I can sign in mergin with official app. Apk keystore is signed. Also, there are some errors at compile output.

> Warning: QML import could not be resolved in any of the import paths: lc
Warning: QML import could not be resolved in any of the import paths: QtQuick.Extras.Private.CppUtils
Warning: QML import could not be resolved in any of the import paths: QtQuick.Extras.Private.CppUtils
Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.Fusion.impl
Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.impl
Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.Material.impl
Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.Imagine.impl
Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.Universal.impl

> Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by PeterPetrik** [comment] 2019-09-27 12:34
those warning are not a problem. Which QT version do you use?

**Comment by berkayoruc** [comment] 2019-09-27 12:56
I am working for android. I did not use docker. Qt Creator version is 4.10.0 and Qt version is 5.13.1. I did not understand how to make instructions for linux about linux for flags.

cd repo/QGIS/build-cmd
cmake \
   -GNinja \
   -DCMAKE_BUILD_TYPE=Release \
   -DCMAKE_INSTALL_PREFIX=~/qmobile/apps \
   -DWITH_GUI=FALSE \
   -DWITH_QUICK=TRUE \
   -DWITH_QTWEBKIT=FALSE \
   -DENABLE_TESTS=FALSE \
   -DWITH_BINDINGS=FALSE \
   ..
ninja
ninja install

and 

#!/bin/bash
APP=~/qmobile/apps

LD_LIBRARY_PATH=$APP/lib/ \
QML2_IMPORT_PATH=$APP/qml \
QGIS_PREFIX_PATH=$APP \
$APP/bin/input

I did not make these are but qt can compile input and generate .apk armeabi-v7a. But I built OSGeo4A and QGIS.

**Comment by PeterPetrik** [comment] 2019-09-30 04:51
first of all, best to use the versions specified in `input-sdk` (we do not use OSGeo4A, but lutraconsulting/input-sdk). version 5.13.1 will not work for now due to some openssl issues., see 

https://github.com/lutraconsulting/input-sdk/blob/master/android/Dockerfile#L6

closing since this is duplicate of https://github.com/lutraconsulting/input-sdk/issues/1

**Closed by PeterPetrik** 2019-09-30 04:51 UTC
Labels: android, mergin
