### ISSUE TITLE
Not giving permissions makes the app unresponsible on Android

### ISSUE THREAD

**Issue by erpas** [lutraconsulting/input#1129] opened 2021-02-03 16:40 UTC
When on tests lutraconsulting/input-manual-tests#25 and https://github.com/lutraconsulting/input-manual-tests/issues/18

Test A - not giving storage and location permissions makes the app unusable on my mobile:

I am not able to get to My Projects as suggested in A7 - I am locked in Home page and cannot sign in nor change a page. The only thing I can, is to enter Create project but then again, I can't finish it, as most of the buttons are not responsible.

On A11 it is very difficult to close the app - the buttons are non-responsible.

Summary, when I accidentally do not give the permission when starting the app for the first time, troubles will inevitably come.

**Comment by saberraz** [comment] 2021-02-04 10:27
Duplicate of https://github.com/lutraconsulting/input/issues/1101

**Closed by saberraz** 2021-02-04 10:27 UTC
Labels: testing bug
