### ISSUE TITLE
This app isn't compatible with your tablet Allegro 3

### ISSUE THREAD

**Issue by waiotahi** [lutraconsulting/input#644] opened 2020-05-05 04:36 UTC
Device is Allegro 3 https://junipersys.com/Products/Allegro-3
OS: Android 7.0 (AOSP)
Processor; 1.2GHz ARM Cortex A9 i.MX6

**Comment by PeterPetrik** [comment] 2020-05-07 06:33
Any change it is running 32bit android ARM system and is duplicate of #641?

**Comment by saberraz** [comment] 2020-05-07 18:01
Please update to 0.6.1 version (released today) and reopen if you still have the issue.

**Closed by saberraz** 2020-05-07 18:01 UTC
Labels: android, blocker, bug
