### ISSUE TITLE
Support for automatic timestamp

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/input#382] opened 2019-07-16 12:57 UTC
When taking photos, it would be very useful to have the date/time automatically added as an attribute value:

![image](https://user-images.githubusercontent.com/884954/61296113-65d56c80-a7d1-11e9-8d84-98d3b2d2f932.png)

I have set up the above form in QGIS so the date field is read-only but has a default value:

![image](https://user-images.githubusercontent.com/884954/61296201-94ebde00-a7d1-11e9-95e5-0a2ae5d6c772.png)

Would Input be able to also populate this field automatically using the default value?

Pete

**Comment by wonder-sk** [comment] 2019-08-06 08:29
Duplicate of #296

**Closed by wonder-sk** 2019-08-06 08:29 UTC
