### ISSUE TITLE
Mixture of groups and single field in Drag-n-Drop designer breaks the form

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1467] opened 2021-06-09 17:39 UTC
If user has a drag-n-drop form designer similar to the one below (normal font: fields, bold font group), Input does not show any of the fields/groups:

- field_1
- **Group1**
- **Group2**
- field_2

See an example of the issue here:
https://public.cloudmergin.com/projects/lutraconsulting/issue_group-field-dnd/tree

**Comment by PeterPetrik** [comment] 2021-06-10 09:23
is this crash?

**Comment by PeterPetrik** [comment] 2021-06-10 09:24
if you have this layout field_1 and field_2 is not shown (as by design), any fields IINSIDE group_1 and group_2 should be shown

**Comment by PeterPetrik** [comment] 2021-06-10 09:25
duplicate of https://github.com/lutraconsulting/input/issues/1458 ?

**Comment by saberraz** [comment] 2021-06-10 11:16
It is a regression which blocks users editing forms from the projects they used to work in earlier version.

**Comment by PeterPetrik** [comment] 2021-06-10 11:58
can you A) please create a project to demonstrate the issue B) state clearly what should be seen in the Input App? 

thanks!

**Comment by saberraz** [comment] 2021-06-10 11:59
See the project in https://github.com/lutraconsulting/input/issues/1467#issue-916455506 which demonstrate the issue. I need to create a screenshot from the previous version of Input.

**Comment by saberraz** [comment] 2021-06-10 12:41
This is how the form appears in 0.9.6:
![Screenshot_20210610-133223_Input](https://user-images.githubusercontent.com/2649047/121526681-84f6cc00-c9f1-11eb-9080-dbd35ea2b195.png)

And how it looks like in this release after form refactoring:
![Screenshot_20210610-132533_Input](https://user-images.githubusercontent.com/2649047/121526766-9cce5000-c9f1-11eb-985a-9dbe92332b92.png)

**Comment by PeterPetrik** [comment] 2021-06-10 12:43
so the groups are "ignored" and all is show as flat?

**Comment by saberraz** [comment] 2021-06-10 12:44
Nothing is shown at all. Neither the groups nor the fields...it is blank:
![Screenshot_20210610-132533_Input](https://user-images.githubusercontent.com/2649047/121527108-f898d900-c9f1-11eb-9d35-e026299a9e43.png)

**Comment by PeterPetrik** [comment] 2021-06-10 12:49
ok!

**Closed** 2021-06-18 08:28 UTC
Labels: bug, forms, regression
