### ISSUE TITLE
Sync status shows sync needed when there are no changes

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/input#1265] opened 2021-03-15 10:30 UTC
On a fresh install of Input (no INPUT folder):

1. Login
2. Download a project which requires a datum shift file to be present
3. Try to load the project, press Ignore when asked about missing .gp? file
4. Go to My Projects (project has sync pending icon next to it)
5. On Home, look at project status: No changes

So here we've made no changes to the project, but on the Home tab, Input is telling us there are pending changes.

When I sync the *changes*, Mergin shows no new version got made.

**Comment by saberraz** [comment] 2021-03-15 11:03
Could you restart the app and see if the issue is still there?

**Comment by saberraz** [comment] 2021-03-22 16:16
I can confirm the issue on iOS.

**Comment by saberraz** [comment] 2021-05-14 08:57
Resolved by https://github.com/lutraconsulting/input/pull/1368

**Closed by saberraz** 2021-05-14 08:57 UTC
Labels: bug, iOS, mergin
