### ISSUE TITLE
Photo not displayed

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/input#388] opened 2019-07-17 07:43 UTC
A valid image is not shown when I open the feature after I try to view a point with invalid photo file reference:

![image](https://user-images.githubusercontent.com/884954/61357994-442bc200-a871-11e9-9898-832d7bf9897e.png)

Steps to reproduce:

0. Close Input
1. Add the attached zip to the mobile device
2. Start Input
3. Zoom to the southern-most point and open it - note you can see the image there (photo2.png)
4. Close it and open the point above it (test.jpg)
5. Close it and open the southern-most one again

I would expect the image (photo2.png) to be displayed but it is not.

[Photo Survey (Template).zip](https://github.com/lutraconsulting/input/files/3400746/Photo.Survey.Template.zip)

**Comment by sklencar** [comment] 2019-08-06 13:58
Cannot be reproducible with[ Input master ](https://github.com/lutraconsulting/input/commit/75d5a235cbf43e73eec3d440ce0b10137fb946fe) and [QGIS](https://github.com/qgis/QGIS/commit/2835ed67321e5efe5893e891c0e4b2c3c0df8b87) - new SDK needed with more recent build of QGIS than ours current SDK.

Let's test to confirm or close the issue after a release of new SDK.

**Comment by saberraz** [comment] 2020-04-19 09:00
No longer reproducible. This was due to the path settings, which seems to be working fine now.

**Closed by saberraz** 2020-04-19 09:00 UTC
Labels: android, bug
