### ISSUE TITLE
Sync button amination doesn't stop

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#2013] opened 2022-03-31 09:32 UTC
There is one situation, when sync button amination doesn't stop. It is when data limit is reached and user hit cancel on the subscription window.

Expected behavior is, that the animation stops when synchronizaton fails

https://user-images.githubusercontent.com/83582181/161024311-1bf180e6-f2aa-4772-af6c-6b7082dacf45.mp4

**Comment by tomasMizera** [comment] 2022-03-31 10:23
@jozef-budac could you please try to reproduce it with latest master? It seems to be fixed now. Please reopen if it is still valid.

**Closed by tomasMizera** 2022-03-31 10:23 UTC
Labels: ui/ux, bug in not released version
