### ISSUE TITLE
Can't upload project after it wa removed on mergin

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1444] opened 2021-06-01 10:32 UTC
After the project is removed from mergin server, project can't be uploaded it again to the mergin.

There is a warning about insufficient rights to do that.  

Steps to reproduce:
1) have synced project on input and mergin
2) remove the project on mergin
3) try to upload the same project from the app

https://user-images.githubusercontent.com/83582181/120309276-57b16c00-c2d5-11eb-9b3b-2dc30f7c9fc7.mp4

**Comment by saberraz** [comment] 2021-06-01 12:37
Duplicate of https://github.com/lutraconsulting/input/issues/1326

**Closed by saberraz** 2021-06-01 12:37 UTC
Labels: bug
