### ISSUE TITLE
app crashes when selecting features containing Value Relation

### ISSUE THREAD

**Issue by p21w** [lutraconsulting/input#1226] opened 2021-03-04 09:41 UTC
I've just created a project with loads of polygons with many attribute widgets.
I've sorted the widgets in the drag/drop designer (which I've had issues with in the app before, but thought I'd give it a try), and I've made multiple value relations. 

Now when I open the project on my phone and select the polygon with the new value relations, the app immediatly crashes. 
Any ideas?

**Comment by saberraz** [comment] 2021-03-04 10:07
Hi @p21w 
Could you make a public project on Mergin (with no sensitive data/information) and post the link here so that we can replicate your issue?

**Comment by p21w** [comment] 2021-03-04 11:28
Not sure how to link it, but here goes:
https://public.cloudmergin.com/projects/p21w/kbhk_tilstandsregistrering_public/tree 

The name is "kbhk_tilstandsregistrering_public" :) 

I've located the problem to being the Value Relation, since I've now actually made a new layer with Value Map, and it seems to be working whereas the old layer with Value Relation still crashes.

**Comment by saberraz** [comment] 2021-03-08 11:58
Hmmm...the project not found. Do you want to upload the project again and we can look at the issue?

**Comment by p21w** [comment] 2021-03-08 12:33
I had to remove it since I don't have enough storage to have two of the projects (o: 

I've made the original project public. It is here: 

https://public.cloudmergin.com/projects/p21w/kbhk_faelledparken1/tree

**Comment by saberraz** [comment] 2021-05-14 09:13
Duplicate of #1257

**Closed by saberraz** 2021-05-14 09:13 UTC
Labels: bug, data corruption - sync failure - crash
