### ISSUE TITLE
[Duplicate] Crash after add new feature

### ISSUE THREAD

**Issue by jozefbudac** [lutraconsulting/input#1332] opened 2021-04-16 09:07 UTC
When I am trying to add new feature, there is sometimes a crash of application.
Unfortunately (or luckily?), the app doesn't crash always. 

Steps to reproduce:
1) download lutraconsulting\test_forms
2) open it
3) try to add feature

https://user-images.githubusercontent.com/78033756/115001127-b8aaef00-9ea3-11eb-94ae-401ba3e289b2.mp4

**Comment by saberraz** [comment] 2021-04-16 09:18
Duplicate of this:
https://github.com/lutraconsulting/input/issues/1281

**Comment by saberraz** [comment] 2021-05-10 11:09
Related to https://github.com/lutraconsulting/input/issues/1035 and duplicate of #1281

**Comment by saberraz** [comment] 2021-05-27 06:41
Resolved after form refactoring.

**Closed by saberraz** 2021-05-27 06:41 UTC
Labels: bug in not released version, data corruption - sync failure - crash, testing
