### ISSUE TITLE
Filter expression for Value Relation widget

### ISSUE THREAD

**Issue by sukuchha** [lutraconsulting/input#402] opened 2019-08-02 05:57 UTC
It would be nice if there is support for Value Relation widget in INPUT

Works fine in QGIS but not working in INPUT

![1](https://user-images.githubusercontent.com/4659586/62347769-85330000-b51a-11e9-99f3-9b107da7a55d.JPG)

**Comment by saberraz** [comment] 2019-08-02 07:12
The feature should be available in the latest Input. Here is my set up:
Non-spatial table containing values:
![image](https://user-images.githubusercontent.com/2649047/62350900-04fda200-b4fc-11e9-9652-252b32e6a100.png)

Survey layer properties, with Value relation:


Edit in QGIS:
![image](https://user-images.githubusercontent.com/2649047/62351371-2ad77680-b4fd-11e9-9e18-acd118f8e166.png)

Edit in Input:
![Uploading image.png…]()

Let me know if you still have issues setting up the widget and I can share my example project on Mergin with you.

**Comment by sukuchha** [comment] 2019-08-03 04:52
saberaz, thank you for taking time to answering. Let me clear what i want.
1) I have GRID shape file, with Grid ID. GRID text (in my picture above) is populated with GRID ID attribute of GRID shape file exactly the way you decribed 
2) I have Building shape file with BIN & GRID ID attributes. BIN text is populated with BIN attribute of Building shape simarly. Now i have set filter expresssion "GRID ID" = current_value('GRID). What it does is if the GRID text is changed, BIN text is automatically changed with BIN associated with that GRID ID. This works perfectly fine in QGIS but on INPUT. With GRID text changed no update on BIN, rather BIN of all GRIDs are displayed.


![2](https://user-images.githubusercontent.com/4659586/62407606-b3781480-b5da-11e9-846b-bf410fcbb3a5.JPG)

explains well in these videos:  1) https://www.youtube.com/watch?v=ipezh4KXrgo by alessandro Pasotti

**Comment by saberraz** [comment] 2019-08-04 16:25
Thanks for clarification. Indeed, this is more of spatial value relation and is not yet supported in Input.

**Comment by saberraz** [comment] 2019-08-20 09:14
https://twitter.com/burdGIS/status/1163737987802443777

**Comment by PeterPetrik** [comment] 2020-05-18 12:47
related to #452

**Comment by saberraz** [comment] 2020-11-12 08:11
Resolved by https://github.com/lutraconsulting/input/pull/1001

**Comment by saberraz** [comment] 2020-11-12 08:11
Duplicate of #740

**Closed by saberraz** 2020-11-12 08:11 UTC
Labels: enhancement, forms, qgis
