### ISSUE TITLE
Cut polygon

### ISSUE THREAD

**Issue by rauledop1** [lutraconsulting/input#1284] opened 2021-03-22 19:17 UTC
There is option to cut polygon in INPUT?

regards

**Comment by PeterPetrik** [comment] 2021-04-15 06:37
No, you can use the QGIS tools when project is transferred to QGIS desktop

**Comment by saberraz** [comment] 2021-04-15 06:48
I think this is feature. Let's have it open as a feature request.

**Comment by saberraz** [comment] 2021-04-15 06:48
Related to #654

**Comment by saberraz** [comment] 2021-06-02 07:39
Duplicate of https://github.com/lutraconsulting/input/issues/471

**Closed by saberraz** 2021-06-02 07:39 UTC
Labels: enhancement, question
