### ISSUE TITLE
Support for filtering options in value relation

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#975] opened 2020-10-26 07:23 UTC
See:
https://public.cloudmergin.com/projects/Mikester/Phase%201%20Collection/tree

![Sab_test](https://user-images.githubusercontent.com/2649047/97144337-2b8ca600-175c-11eb-8b36-b448da859157.JPG)

**Comment by wonder-sk** [comment] 2020-10-26 07:37
Duplicate of #740 ?

**Comment by saberraz** [comment] 2020-10-26 07:45
Indeed...

**Closed** 2020-10-26 07:45 UTC
Labels: forms, qgis
