### ISSUE TITLE
Downloaded project crashes after adding a feature

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#1020] opened 2020-11-20 10:45 UTC
This bug can be reproduced consistently in iOS, but in Android, it generally works:
- Open an existing local project
- Download one your project
- Open the freshly downloaded project
- Add a new feature
- Crash

**Comment by saberraz** [comment] 2020-11-20 18:07
Seems to be with specific projects. We can park that for the time being and look at those projects in more details in future.

**Comment by PeterPetrik** [comment] 2020-11-23 09:24
based on crashreport it could be duplicate of https://github.com/lutraconsulting/input/issues/1011

**Comment by PeterPetrik** [comment] 2020-11-23 10:07
<img width="1475" alt="Screenshot 2020-11-23 at 11 05 50" src="https://user-images.githubusercontent.com/804608/99949784-de601c00-2d7b-11eb-80f1-dfe42bc55116.png">

**Comment by PeterPetrik** [comment] 2020-11-25 14:50
to replicate it more consistenty:
- open lutraconsulting/test_digitizing
- add new area feature
- delete one point feature
- switch to other project 💥

**Closed** 2020-11-26 11:27 UTC
Labels: bug, data corruption - sync failure - crash, iOS, testing bug
