### ISSUE TITLE
Date and time field breaks sometimes

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1381] opened 2021-05-06 19:15 UTC
Insertion of data sometimes work for a date&time field and sometimes don't

Best way to simulate is to create new feature with this field and try to insert some letters. But it is not always.
Please check the video to see more:

https://user-images.githubusercontent.com/83582181/117353234-2d27eb00-aeb0-11eb-88e3-747ee5000a0f.mp4

**Comment by saberraz** [comment] 2021-05-07 06:44
@jozef-budac is it not duplicate of #1377 ?

**Comment by jozef-budac** [comment] 2021-05-10 06:17
Yes, I see this ticket as a duplicate of #1377

**Closed** 2021-05-10 10:45 UTC
Labels: testing bug
