### ISSUE TITLE
Update user subscription info endpoint 

### ISSUE THREAD

**Issue by sklencar** [lutraconsulting/input#1442] opened 2021-06-01 08:27 UTC
Update user subscription info endpoint according:
https://gitlab.cloud.lutraconsulting.co.uk/mergin/mergin/-/issues/668

The change is due to CE support and currently using not dedicated endpoint for it.

**Comment by wonder-sk** [comment] 2021-06-01 08:47
Duplicate of #1375 ?

**Comment by sklencar** [comment] 2021-06-01 10:49
Duplicate of #1375

**Closed** 2021-06-01 10:49 UTC
Labels: mergin
