### ISSUE TITLE
multiline text edit keyboard blocks Save

### ISSUE THREAD

**Issue by gubuntu** [lutraconsulting/input#592] opened 2020-03-10 08:28 UTC
If you hit Enter while editing a multiline field it just adds another line. You have to tap another tab or device backspace to close the keyboard so you can see the Save button.

**Comment by saberraz** [comment] 2020-05-22 16:14
The correct UI for this should be similar to other apps, where the green bar should move above the keyboard.

**Comment by saberraz** [comment] 2020-08-04 07:02
Duplicate of https://github.com/lutraconsulting/input/issues/384

**Closed by saberraz** 2020-08-04 07:02 UTC
Labels: bug, forms, ui/ux
