### ISSUE TITLE
Icons in settings are small

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#86] opened 2018-11-28 10:37 UTC
The "Follow GPS map" turn on/off and "Acceptable GPS accuracy" settings are small and a bit difficult to change.
![screenshot_20181128-103323_input](https://user-images.githubusercontent.com/2649047/49146122-63cda480-f2f9-11e8-927b-c8cb8107e1c9.png)

**Comment by wonder-sk** [comment] 2018-11-28 10:53
Duplicate of #75

**Closed by wonder-sk** 2018-11-28 10:53 UTC
