### ISSUE TITLE
Not Null Constraints Enforced in QGIS form is not Applied on Input

### ISSUE THREAD

**Issue by seabilwe** [lutraconsulting/input#831] opened 2020-08-10 20:57 UTC
I have enforced _not null_ constraints (image below) on survey questions in a QGIS form so that each question answered using Input is not skipped, but in this case, a surveyor is able to save and sync with some questions left unanswered. How can one fix this?
![constraints](https://user-images.githubusercontent.com/56301949/89830304-3de34480-db5c-11ea-952f-322394d8bbcb.JPG)

**Comment by saberraz** [comment] 2020-08-14 08:59
Hi @seabilwe 
This looks like duplicate of #458 ?

**Comment by seabilwe** [comment] 2020-08-14 11:13
Hi @saberraz 

Ahh yes! 

Thank you! Funny I missed it when I was checking if a similar issue was placed

**Comment by wonder-sk** [comment] 2020-08-18 09:13
Cool... I will close this ticket, any progress updates would go to #458

**Closed by wonder-sk** 2020-08-18 09:13 UTC
