### ISSUE TITLE
App is very slow without location permission

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1389] opened 2021-05-10 10:25 UTC
Without location permission, the app is almost unusable. It is too slow to do anything.

https://user-images.githubusercontent.com/83582181/117645219-a3676e80-b18a-11eb-80ca-11ef8be82830.mp4

**Comment by tomasMizera** [comment] 2021-05-27 09:36
Duplicate of #1101 and related to #1057

**Comment by tomasMizera** [comment] 2021-09-27 09:48
Closing since it is a duplicate

**Closed by tomasMizera** 2021-09-27 09:48 UTC
Labels: bug
