### ISSUE TITLE
Project without QGIS project file can't be synchronized 

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input#1493] opened 2021-06-16 08:35 UTC
When there is a project without QGIS project file, it can't be synchronized even after the project file was added into the project.
The project can be removed and download again, but I would expect, synchronization from mergin can work for such a projects.

**Comment by wonder-sk** [comment] 2021-07-09 08:22
Duplicate of #1547

**Closed by wonder-sk** 2021-07-09 08:22 UTC
Labels: enhancement, mergin
