### ISSUE TITLE
Containers and groups in "Drag and drop designer" don't all show

### ISSUE THREAD

**Issue by p21w** [lutraconsulting/input#1229] opened 2021-03-04 11:33 UTC
I've found that the "Drag and drop designer" now work on input, which is great!

But when creating a design with both containers and groups in the "Drag and drop designer", the app only shows the groups.
I'm thinking it might be because the app can't tell the difference between containers and groups and therefore sorts out the containers. 

I get a long list of my widgets shown in groups. I'd prefer tabs to choose from (as in QGIS), where I choose which container to work within and there see my groups. Alternatively it would be nice to just see when I switch containers in the long list :)

**Comment by saberraz** [comment] 2021-03-04 11:57
Is this not duplicate of this other ticket:
https://github.com/lutraconsulting/input/issues/232

There is a bug when you have groups and individual fields. The work-around is to have everything in groups and avoid having individual field(s) in your layout.

**Comment by p21w** [comment] 2021-03-04 20:46
Hmm it seems to be similar
But I have both groups and sub-groups. It's only the sub-groups headlines, that show. It generally just means I can't see which group I'm in. I'll post pictures

**Comment by p21w** [comment] 2021-03-05 08:08
![image](https://user-images.githubusercontent.com/80035971/110086212-6352cc80-7d92-11eb-840d-b7557ab8443f.png)

**Comment by p21w** [comment] 2021-03-05 08:09
![image](https://user-images.githubusercontent.com/80035971/110086321-82515e80-7d92-11eb-95f6-730a51332a83.png)

**Comment by p21w** [comment] 2021-03-05 08:11
So the first picture shows the design on QGIS, where I can choose between the different categories (containers) "parkbevoksninger", "landskabsbevoksninger", "prydbuske" and "udfyldes ikke". 
Two widgets are not in a group.

On my phone I see the widgets which are ungrouped, but I can't see my different categories (containers). It only shows the groups

**Comment by saberraz** [comment] 2021-03-05 08:15
hi @p21w 

This is the issue I was mentioning. The workaround is:
Move **tilstands_score** and **tilstand_score_pryd** fields to **parkbevoksninger** (or create a new group and move those two fields there). There is a bug with qgisquick form which cannot handle Groups + individual fields.

**Comment by saberraz** [comment] 2021-04-19 13:03
Duplicate of #232

**Closed by saberraz** 2021-04-19 13:03 UTC
Labels: bug, forms
