### ISSUE TITLE
Ignore &#xd; in Display

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#412] opened 2019-08-19 15:05 UTC
When I copy and paste:
```
# image
file:///[%@project_folder%]/[% "Photo" %]
```
It turns to this in my project:
```
<mapTip># image&#xd;
file:///[%@project_folder%]/[% "Photo" %]</mapTip>
```

Is there a way to ignore parsing the extra junk, as users are not aware of this and causes the pop up not to work.

**Comment by wonder-sk** [comment] 2019-08-19 15:36
@saberraz Duplicate of https://github.com/lutraconsulting/input/issues/387 ? :-) It should be fixed in the most recent master...

**Closed** 2019-08-19 15:41 UTC
Labels: bug
