### ISSUE TITLE
Reverse sorting order for Diagnostic log

### ISSUE THREAD

**Issue by chris9404** [lutraconsulting/input#1713] opened 2021-10-19 09:57 UTC
Hi all

I needed to check what happened after a weird issue, and had to scroll through 2 months' worth of logs to find the latest stuff.
I initially didn't notice the scroll bar since the icon is extremely small with this amount of logs. Even after noticing it, it takes about 10 tries to grab hold of it.

Its not a major issue at all, but quite irritating when you do need to look at the logs.

**Comment by PeterPetrik** [comment] 2021-11-08 14:29
duplicate of #1521

**Closed by PeterPetrik** 2021-11-08 14:29 UTC
