### ISSUE TITLE
Feature information - crash when selecting multipolygons or polygons with rings

### ISSUE THREAD

**Issue by dracic** [lutraconsulting/input#1322] opened 2021-04-13 16:03 UTC
Project dracic/sumarija-novi-vinodolski
layer: ods

Saber has access to my project

Try polygons on south edge

**Comment by saberraz** [comment] 2021-04-14 11:15
Isn't this duplicate of https://github.com/lutraconsulting/input/issues/1182?

**Comment by dracic** [comment] 2021-04-14 17:50
This time Input crashes completely when selecting polygons. It is not just wrong highlighting.

**Closed** 2021-04-19 12:05 UTC
Labels: bug, data corruption - sync failure - crash
