### ISSUE TITLE
Ability to take multiple photos for a single feature

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input#356] opened 2019-07-02 06:09 UTC
Currently, to do that, user will have to create multiple fields for the surveyed layer. But, it will be good to have an option to attache multiple photos to one (virtual) field. This might require an upstream feature enhancement in QGIS.

**Comment by wonder-sk** [comment] 2019-07-02 06:36
Duplicate of #15 and #27 ?

**Closed** 2019-07-02 06:40 UTC
Labels: enhancement
